services:
  devcontainer:
    container_name: ${CONTAINER_NAME:-ProjectName}
    hostname: ${HOSTNAME:-projectname}
    image: ${IMAGE_NAME:-ProjectName:latest}
    build:
      context: .
      args:
        APP_GID: ${APP_GID:-1000}
        APP_UID: ${APP_UID:-1000}
        APP_USER: ${APP_USER:-appuser}
        APP_GROUP: ${APP_GROUP:-appgroup}
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-8.9}
    env_file:
      - .env
    volumes:
      - SyntheticData_src:/app
    working_dir: /app
    user: "${APP_RUNTIME_GID:-1000}:${APP_RUNTIME_GID:-1000}"
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${NVIDIA_GPU_COUNT:-all}
              capabilities: [gpu]

volumes:
  SyntheticData_src:

networks:
  default:
    name: ${NETWORK_NAME:-project_network}
